{% set version = "3.2.2" %}

package:
  name: cutlass
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cutlass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aaa9719eb806b168695b34893faf4854bb6bc9e09f63f2d36772aaf35a8516e5

build:
  number: 1
  skip: true  # [osx or cuda_compiler_version not in ("12.0",)]
  ignore_run_exports_from:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja
  run_constrained:
    - cuda-version >=11.0.*,<13.a0

test:
  requires:
    - tree  # [linux]
  commands:
    # headers:
    - tree $CONDA_PREFIX/include/cutlass  # [linux]
    - tree $CONDA_PREFIX/include/cute  # [linux]
    - tree %CONDA_PREFIX%\Library\include\cutlass  # [win]
    - tree %CONDA_PREFIX%\Library\include\cute  # [win]

about:
  home: https://github.com/NVIDIA/cutlass
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CUDA Templates for Linear Algebra Subroutines
  dev_url: https://github.com/NVIDIA/cutlass

extra:
  recipe-maintainers:
    - h-vetinari
    - RaulPPelaez
    - leofang
