{% set version = "3.1.0" %}

package:
  name: cutlass
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cutlass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 821aa2e5b709a2e5d3922dcf2c5d445b4898a6ef8bac683cfb00125eafbca029

build:
  number: 2
  skip: true  # [osx]
  run_exports:
    - {{ pin_subpackage('cutlass', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
  host:
    - cudnn
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
  run:
    - cudnn
test:
  commands:
    # headers:
    # This list should be substantially longer, but upstream just globs
    # all *.h files. These are the headers required for triton, but
    # relevant headers can be added as needed/desired.
    {% for each_header in ["library/handle.h", "library/library.h",
                           "library/operation_table.h", "library/singleton.h"] %}
    - test -f $PREFIX/include/cutlass/{{ each_header }} || (echo "{{ each_header }} not found" && exit 1)  # [unix]
    - if not exist %LIBRARY_INC%\cutlass\{{ "\\".join(each_header.split("/")) }} exit 1                    # [win]
    {% endfor %}

about:
  home: https://github.com/NVIDIA/cutlass
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CUDA Templates for Linear Algebra Subroutines
  dev_url: https://github.com/NVIDIA/cutlass

extra:
  recipe-maintainers:
    - h-vetinari
    - RaulPPelaez
    - leofang
