{% set version = "3.1.0" %}

package:
  name: cutlass
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cutlass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 821aa2e5b709a2e5d3922dcf2c5d445b4898a6ef8bac683cfb00125eafbca029

build:
  number: 2
  skip: true  # [osx or cuda_compiler_version not in ("12.0",)]
  run_exports:
    - {{ pin_subpackage('cutlass', max_pin='x.x') }}
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
    - ninja  # [win64]
  run_constrained:
    - cuda-version >=11.0.*,<13.a0
test:
  requires:
    - tree  # [linux]
  commands:
    # headers:
    - tree $CONDA_PREFIX/include/cutlass  # [linux]
    - tree %CONDA_PREFIX%\Library\include\cutlass  # [win]

about:
  home: https://github.com/NVIDIA/cutlass
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CUDA Templates for Linear Algebra Subroutines
  dev_url: https://github.com/NVIDIA/cutlass

extra:
  recipe-maintainers:
    - h-vetinari
    - RaulPPelaez
    - leofang
