conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
github_actions:
  self_hosted: true
  timeout_minutes: 720
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
